// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnwjljnvzqmbfzjwhzyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdud2psam52enFtYmZ6andoenlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODk4ODgsImV4cCI6MjA2MDA2NTg4OH0.Xs_Eb42mG6TUn83c299UctLXUuOrot5DngRzZCHgzUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);